### ISSUE TITLE
feat: 24.01.08 ~ 24.01.13 그리디 공유 문제

### ISSUE THREAD

**Issue by mun-jihye** [sihyonn/codingTest-study#20]
## Description
그리디 알고리즘 공유 문제

## Todo

- [x] [[1931번: 회의실 배정](https://www.acmicpc.net/problem/1931)](https://www.acmicpc.net/problem/1931)

- [x] [[1715번: 카드 정렬하기](https://www.acmicpc.net/problem/1715)](https://www.acmicpc.net/problem/1715)

- [x] [[1744번: 수 묶기](https://www.acmicpc.net/problem/1744)](https://www.acmicpc.net/problem/1744)
## ETC
pr 날릴때 이슈 넘버 기입해주기
