### ISSUE TITLE
24.01.22 ~ 24.01.26 이진 탐색 공유문제

### ISSUE THREAD

**Issue by mun-jihye** [sihyonn/codingTest-study#54]
## Description
이진 탐색 알고리즘 공유 문제

## Todo

- [x] [[2805번: 나무 자르기](https://www.acmicpc.net/problem/2805)](https://www.acmicpc.net/problem/2805)
- [x] [[1654번: 랜선 자르기](https://www.acmicpc.net/problem/1654)](https://www.acmicpc.net/problem/1654)
- [x] [[2110번: 공유기 설치](https://www.acmicpc.net/problem/2110)](https://www.acmicpc.net/problem/2110)
