### ISSUE TITLE
24.01.29 ~ 24.02.03 이진 탐색 공유문제 

### ISSUE THREAD

**Issue by Hooni07** [sihyonn/codingTest-study#65]
## Description
이진 탐색 알고리즘 공유 문제

## Todo

- [x] [[2343번: 기타 레슨](https://www.acmicpc.net/problem/2343)](https://www.acmicpc.net/problem/2343)
- [x] [[2470번: 두 용액](https://www.acmicpc.net/problem/2470)](https://www.acmicpc.net/problem/2470)
- [x] [[2512번: 예산](https://www.acmicpc.net/problem/2512)](https://www.acmicpc.net/problem/2512)
