### ISSUE TITLE
24.02.05 ~ 24.02.17 DFS, BFS 공유문제

### ISSUE THREAD

**Issue by Hooni07** [sihyonn/codingTest-study#81]
## Description
DFS 및 BFS 알고리즘 공유 문제

## Todo

- [x] [[2606번: 바이러스](https://www.acmicpc.net/problem/2606)](https://www.acmicpc.net/problem/2606)
- [x] [[2178번: 미로 탐색](https://www.acmicpc.net/problem/2178)](https://www.acmicpc.net/problem/2178)
- [x] [[11725번: 트리의 부모 찾기](https://www.acmicpc.net/problem/11725)](https://www.acmicpc.net/problem/11725)
- [x] [[4963번: 섬의 개수](https://www.acmicpc.net/problem/4963)](https://www.acmicpc.net/problem/4963)
- [x] [[2644번: 촌수계산](https://www.acmicpc.net/problem/2644)](https://www.acmicpc.net/problem/2644)
